export const Regions = [
    {
        id:1,
        nom:"CENTRE",
        departements:[
            {
                id:1,
                nom:"LEKIE",
                arrondissements:[
                    {
                        id:1,
                        nom:"SAA"
                    },
                    {
                        id:2,
                        nom:"MONATELE"
                    },
                    {
                        id:3,
                        nom:"EBEBDA"
                    },
                    {
                        id:4,
                        nom:"OBALA"
                    },
                    {
                        id:5,
                        nom:"OKOLA"
                    },
                    {
                        id:6,
                        nom:"ELIG-MFOMO"
                    },
                    {
                        id:7,
                        nom:"EVODOULA"
                    },
                    {
                        id:8,
                        nom:"BATCHENGA"
                    },
                    {
                        id:9,
                        nom:"LOBO"
                    }
                ]
            },
            {
                id:2,
                nom:"MBAM et ENOUBOU",
                arrondissements:[
                    {
                        id:1,
                        nom:"BAFIA"
                    },
                    {
                        id:2,
                        nom:"OMBESSA"
                    },
                    {
                        id:3,
                        nom:"NDIKINIMEKI"
                    },
                    {
                        id:4,
                        nom:"BOKITO"
                    },
                    {
                        id:5,
                        nom:"DEUK"
                    },
                    {
                        id:6,
                        nom:"MAKENENE"
                    },
                    {
                        id:7,
                        nom:"KIKI"
                    },
                    {
                        id:8,
                        nom:"KON-YAMBETA"
                    },
                    {
                        id:9,
                        nom:"NITOUKOU"
                    }
                ]
            }
        ]
    }
]